# Generated by Django 5.2.8 on 2025-11-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=5, unique=True)),
            ],
            options={
                'verbose_name': 'Размер одежды',
                'verbose_name_plural': 'Размеры одежды',
                'ordering': ['size'],
            },
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10'), ('10.5', '10.5'), ('11', '11'), ('11.5', '11.5'), ('12', '12'), ('13', '13')], max_length=5, unique=True)),
            ],
            options={
                'verbose_name': 'Размер обуви',
                'verbose_name_plural': 'Размеры обуви',
                'ordering': ['size'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shoes', 'Обувь'), ('clothing', 'Одежда'), ('accessories', 'Аксессуары')], default='accessories', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='clothing_sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.clothingsize'),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.shoesize'),
        ),
    ]
